/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;




import static Admin.Facerecog.embedFace;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import image.JPGInterpreter;
import image.ImageConversionContext;




/**
 *
 * @author abder
 */
public class addemp extends javax.swing.JPanel {

     public static void main(String[] args) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame("Add Employee");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new addemp());
            frame.pack();
            frame.setVisible(true);
        });
    }
    /**
     * Creates new form 
     */
     public addemp() {
        initComponents();
        setVisible(true); // Set the frame visible when it's created
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        addemp = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        image = new javax.swing.JFileChooser();
        fname = new javax.swing.JTextField();
        lrole = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        progressbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addemp.setBackground(new java.awt.Color(102, 255, 102));
        addemp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addemp.setText("ADD EMPLOYEE");
        addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancel.setText("CLOSE");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        image.setAcceptAllFileFilterUsed(false);
        image.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FIRST NAME:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ROLE:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lrole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lrole, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancel)
                        .addComponent(addemp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempActionPerformed
        // Get input values from the UI components
        DBWriter dbwriter= new DBWriter();
String firstName = fname.getText();
String lastName = lrole.getText();
String employeeRole = role.getText();
File selectedFile = image.getSelectedFile();
String id=dbwriter.generateNextId();

// Validate input fields
if (firstName.isEmpty() || lastName.isEmpty() || employeeRole.isEmpty() || selectedFile == null) {
    JOptionPane.showMessageDialog(this, "All fields are obligatory", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Instantiate an Employee object
Employee employee = new Employee.EmployeeBuilder()
        .setFname(firstName)
        .setLname(lastName)
        .setRole(employeeRole)
        .setid(id)
        .build();

System.out.println("Employee: " + employee);

// Convert the selected image file to JPG format using the PNGInterpreter
BufferedImage inputImage;
try {
    inputImage = ImageIO.read(selectedFile);
    System.out.println("Input Image Loaded");

    JPGInterpreter interpreter = new JPGInterpreter(); // 
    ImageConversionContext conversionContext = new ImageConversionContext(inputImage, interpreter);
    BufferedImage outputImage = conversionContext.interpretImage();

    System.out.println("Image Converted to JPG");

    // Create a directory for the employee's images if it does not exist
    String employeeDirectoryPath = "C:/PROJECTS/teneleven/employees/" + id;
    File employeeDirectory = new File(employeeDirectoryPath);
    if (!employeeDirectory.exists()) {
        if (!employeeDirectory.mkdirs()) {
            JOptionPane.showMessageDialog(this, "Failed to create employee directory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    // Save the converted image to a file in the employee directory
    File outputImageFile = new File(employeeDirectory, "output.JPG");
    ImageIO.write(outputImage, "JPG", outputImageFile);
    System.out.println("Output Image Saved");
    dbwriter.addEmployee(employee);
    // Perform additional operations with the employee object
    // (e.g., save to database, trigger face recognition, etc.)

    // Update UI or perform any other necessary actions
} catch (IOException ex) {
    JOptionPane.showMessageDialog(this, "Error reading image file", "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}

javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
    int progress = progressbar.getValue();
    if (progress < 100) {
        progress += 10; // Increment progress by 10% every second
        progressbar.setValue(progress);
    } else {
        ((javax.swing.Timer) e.getSource()).stop(); // Stop the timer when progress reaches 100%
    }
});
timer.setInitialDelay(0); // Start immediately
timer.start();

// Run the embedFace function in a separate thread
new Thread(() -> {
    embedFace("C:/PROJECTS/teneleven/employees");
}).start();


    }//GEN-LAST:event_addempActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
   
    SwingUtilities.getWindowAncestor(this).dispose();

    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemp;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField fname;
    private javax.swing.JFileChooser image;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lrole;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JTextField role;
    // End of variables declaration//GEN-END:variables
}
