/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author abder
 */
public class Settings extends javax.swing.JPanel {
    private final DBWriter dbWriter;

    /**
     * Creates new form NewJPanel
     */
    public Settings() {
        this.dbWriter = new DBWriter();
        initComponents();
    }
  public static void main(String[] args) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame("Settings");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new Settings());
            frame.pack();
            frame.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cleanlog = new javax.swing.JButton();
        cleanemp = new javax.swing.JButton();
        archive = new javax.swing.JButton();
        close = new javax.swing.JButton();
        sqlsttm = new javax.swing.JTextField();
        EXECSQL = new javax.swing.JButton();

        cleanlog.setText("CLEAN ALL LOGS");
        cleanlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanlogActionPerformed(evt);
            }
        });

        cleanemp.setText("REMOVE ALL EMPLOYEES");
        cleanemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanempActionPerformed(evt);
            }
        });

        archive.setText("ARCHIVE LOGS");
        archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        sqlsttm.setText("sql");

        EXECSQL.setText("EXECUTE");
        EXECSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXECSQLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sqlsttm, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(EXECSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 229, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cleanlog, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(cleanemp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(archive, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanlog, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanemp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EXECSQL, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(sqlsttm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cleanempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanempActionPerformed
         // TODO add your handling code here:
          try {
            dbWriter.deleteAllEmployees();
            // Display success message or update UI accordingly
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Display error message or handle exception
        }
    }//GEN-LAST:event_cleanempActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
    SwingUtilities.getWindowAncestor(this).dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveActionPerformed
        // TODO add your handling code here:
         try {
            dbWriter.exportAllLogsToCSV();
            // Display success message or update UI accordingly
        } catch (SQLException | IOException ex) {
            ex.printStackTrace();
            // Display error message or handle exception
        }
    }//GEN-LAST:event_archiveActionPerformed

    private void cleanlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanlogActionPerformed
        // TODO add your handling code here:
          try {
            dbWriter.deleteAllLogs();
            // Display success message or update UI accordingly
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Display error message or handle exception
        }
    }//GEN-LAST:event_cleanlogActionPerformed

    private void EXECSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXECSQLActionPerformed
        // TODO add your handling code here:
          String sqlCommand = sqlsttm.getText();
        try {
            dbWriter.executeSQLCommand(sqlCommand);
            // Display success message or update UI accordingly
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Display error message or handle exception
        }
    }//GEN-LAST:event_EXECSQLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXECSQL;
    private javax.swing.JButton archive;
    private javax.swing.JButton cleanemp;
    private javax.swing.JButton cleanlog;
    private javax.swing.JButton close;
    private javax.swing.JTextField sqlsttm;
    // End of variables declaration//GEN-END:variables
}
